### ISSUE TITLE
Push 0.1.2 onto crates.io

### ISSUE THREAD

**Issue by Oberdiah** [Lichtso/contrast_renderer#2]
Hi, loving the renderer, I'm finding it very helpful for the project I'm working on.

However, I'm having to point my version at this repository, as crates.io only has 0.1.1. It would be great if you could put this newest version (supporting wgpu 0.16) onto crates.io.

Thanks!

**Comment by Lichtso** [comment]
I was waiting for wgpu 0.17 to be released. Usually it would be every quarter but it is somehow running late.

**Comment by Lichtso** [comment]
It was released a day after my comment :)

Anyway, published v0.1.2 to [crates.io](https://crates.io/crates/contrast_renderer) now.
